USE Garage;

CREATE TABLE Automobile (
  Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
  Make VARCHAR(50) NOT NULL,
  Model VARCHAR(50) NOT NULL,
  [Year] INT NOT NULL,
  [Name] VARCHAR(100) NOT NULL,
  Last_Service_Date DATETIME NULL
);