FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ./DbUp /src

RUN dotnet build -c Debug -o /app/build
RUN dotnet publish -c Debug -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT [ "dotnet", "DbUp.dll" ]